# Generated by Django 4.1.7 on 2023-03-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('sno', models.IntegerField()),
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('userpass', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('quantity', models.IntegerField()),
                ('subtotal', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
                ('category_info', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryToProduct',
            fields=[
                ('category_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('category_to_product_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'category_to_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=45)),
                ('cust_pass', models.CharField(max_length=45)),
                ('cust_type', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('residence', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('selling_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('category_name', models.CharField(max_length=45)),
                ('product_name', models.CharField(max_length=45)),
                ('brand_name', models.CharField(max_length=45)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(blank=True, null=True)),
                ('descript', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('bill_no', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_purchase', models.DateField()),
            ],
            options={
                'db_table': 'ledger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductToBrand',
            fields=[
                ('product_id', models.IntegerField()),
                ('brand_id', models.IntegerField()),
                ('product_to_brand_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_to_brand',
                'managed': False,
            },
        ),
    ]
